# Copyright 2023 Datum Technology Corporation
# SPDX-License-Identifier: GPL-3.0
########################################################################################################################


[project]
name        = "mio_demo"
full-name   = "Moore.io CLI Demo"
description = ""
