# Copyright 2022 Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[project]
name        = "mio_demo"
full-name   = "Moore.io CLI Demo"
description = ""

[simulation]
preferred-simulators = [ "vivado" ]
